baseURL = "https://cis527.russfeld.me/"
languageCode = "en-us"
title = "K-State CIS 527 Online"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
page = [ "HTML", "Iframeable", "Teleprompter"]
section = [ "HTML", "Iframeable", "Teleprompter"]

[params]
  editURL = "https://gitlab.cs.ksu.edu/russfeld/cis527online/tree/master/content/"
  description = "K-State CIS 527 Curriculum Repository"
  author = "Russell Feldhausen"
  showVisitedLinks = false
  themeVariant = "purple"
  disableLanguageSwitchingButton = true

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[outputFormats]
  [outputFormats.Iframeable]
    name = "Iframeable"
    baseName = "embed"
    mediaType = "text/html"
    isPlainText = false
    isHTML = true
  [outputFormats.Teleprompter]
    name = "Teleprompter"
    baseName = "tele"
    mediaType = "text/html"
    isPlainText = false
    isHtml = true
